# Generated by Django 4.2.26 on 2025-12-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_baletoken_device_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baletoken',
            name='bale_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
