# Generated by Django 4.2.26 on 2025-12-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_baletoken_bale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baletoken',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='baletoken',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
