# Generated by Django 4.2.26 on 2025-12-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_baletoken_first_name_baletoken_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baletoken',
            name='username',
        ),
    ]
