# Generated by Django 4.2.26 on 2026-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_baletoken_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baletoken',
            name='received_at',
        ),
        migrations.AlterField(
            model_name='baletoken',
            name='bale_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baletoken',
            name='device_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='baletoken',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baletoken',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
