# Generated by Django 4.2.26 on 2026-01-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_remove_baletoken_received_at_alter_baletoken_bale_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baleaccount',
            name='user_id',
        ),
        migrations.AddField(
            model_name='baleaccount',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
