# Generated by Django 4.2.26 on 2025-11-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
