# Generated by Django 4.2.26 on 2025-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_page_url_page_page_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_name',
            new_name='page_url',
        ),
        migrations.AddField(
            model_name='page',
            name='Internal_link',
            field=models.BooleanField(default=True),
        ),
    ]
