# Generated by Django 4.2.26 on 2025-11-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_page_name_page_page_url_page_internal_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Internal_link',
            new_name='internal_link',
        ),
    ]
